### PR TITLE
ADDED: External function for testing for metadata

### PR DESCRIPTION
**Pull request by jasedit**
Adds function which can test for existence of metadata from a C-style string, useful for using MMD6 from an external interface.

### CODE REVIEW

**Comment by fletcher** [comment]
`token_pool`s are not necessarily used, so any `init()` or `free()` calls have to be wrapped in `#ifdef kUseObjectPool`.

Token pools allocate large slabs of memory for tokens in a single step, rather than allocating them one at a time.  This means that they have to be free'd in a single step as well.  Which means they can only be free'd when we're sure they won't be used again.

I think what I'll do instead of accepting this request is define a clear naming convention for functions in `libMultiMarkdown.h` that specify whether we handle a text string, or a `mmd_engine`.  That should solve some of the issues you are pointing out.

Once I do that, I'll either accept or reject the remaining pull requests as appropriate, but all the functionality should be implemented.

Thanks!!

**Comment by jasedit** [comment]
Let me know if there's anything I can do to help - I'm happy to adjust PRs or rewrite code as needed to help speed along development.

**Comment by fletcher** [comment]
I was out of town for a few days, but am back.  Working on software today.

Thanks!

**Comment by fletcher** [comment]
Also -- since token pools are handled globally, they should only be init`ed and free`d by the "master" program -- in our case, this is in `main.c`, *or* by the developer of the main program.  *not* within our library.

I'll probably just disable it by default to simplify things for others.

**Comment by jasedit** [comment]
As someone who is coming from this as an external integrator, it doesn't surprise me that there's a need to setup and teardown functionality for the library. The challenge came in trying to determine the public interface from the header file, which I took as the definition of the public interface. There are several functions which seem to be part of the external interface, but are defined elsewhere and appear to be internal details (e.g. the token pool init/free, `transclude_source`).

It may be useful to make the high level public interface a bit more explicitly separated, and provide matching high level functions for the init/free stages? If I had seen an `mmd_init()` and `mmd_free()` call, I would have likely investigated these are possible requirements for using the library, and would have zero issues with having to call those as part of using the library.

**Comment by fletcher** [comment]
Conceptually, it's probably best to think of the project as several separate pieces:

1. Token pool as above -- I added a bit of instruction to `libMultiMarkdown.h` about this.  My recommendation is to simply disable token pools unless you absolutely need highest performance, and understand how they work.  Most people don't need them.

2. Transclusion -- also tricky, and technically separate from MMD itself.  Transclusion requires access to the disk directory, and can generate security risks.  You'll notice that all transclusion functionality is handled in `main.c`, *not* in libMultiMarkdown itself.

3. Ditto with CriticMarkup.

4. libMMD proper -- handles conversion of text to HTML/LaTeX/EPUB/etc.

**Comment by fletcher** [comment]
I implemented all of the functionality you included in your pull requests, but did it slightly differently.

Let me know if you have any questions or something doesn't work as expected.  

I *think* the new function naming conventions should clarify a few things.

**Comment by fletcher** [comment]
PS>  It's not to say that I'll never consolidate key functions from transclusion or CriticMarkup in the main header file, but I need to be sure it's done correctly and safely.

**Comment by jasedit** [comment]
The token pool issue I need to dig into in greater detail, since as far as I could tell, it's something that needs to be initialized and freed up at the start and end of a program's lifetime, which isn't too complex. There are challenges with using the library externally given how it's currently implemented, since the flag indicating if token pools are enabled or not is not accessible at runtime. If a project custom builds its own copy, everything can be made to work, but sharing a copy means copy has to guess if the token pool is in use.

As for the other features, the problem is that from a library perspective, transclusion and CriticMarkup are explicitly part of MultiMarkdown. A MultiMarkdown document includes those directives, and the expected behavior requires including that bit of functionality. The [pymmd](https://github.com/jasedit/pymmd) library I've written with has to support those features to provide support for converting MMD documents, so for those cases, I have to hunt down those features and implement interfaces to them. It obviously works as-is, but it presents an uneven interface to have some functionality behind fairly public looking function calls, and other parts requiring more knowledge of the implementation details.

Obviously this is all just my two cents. If it doesn't fit your vision for the tool, it doesn't fit. Thanks again for the great tool and hard work you put into it!

**Comment by fletcher** [comment]
The token pool will continue to allocate space as long it parses text.  If you process documents over and over without quitting the process (or draining the pool), you will eventually run out of space.

If you run a command-line utility, this doesn't usually matter.  As you said, init at the beginning, and free (or don't) when you quit.  But if you batch *a lot* of files, you might want to init/drain/free the pool for each file.

But something like MultiMarkdown Composer, which can parse the multiple files thousands of times each, needs a more nuanced approach.  You can't drain the token pool until you are sure that the current tokens in use are no longer needed, and libMMD doesn't have access to that knowledge.  And since there is only one pool, this is particularly tricky in a multi-threaded application.

Unless you really need to squeeze every last bit of performance, it's best to turn token pools off.

CriticMarkup is actually handled in two different ways -- one is handled "inside" the MMD processing and works any time.  The other is the "pre-processing" approach, accessed via the command-line options (`-a` or `-r`).  This is handled external to the library because it happens before MMD processing.  (CriticMarkup is, by definition, orthogonal to MMD -- it will break HTML validity under many situations.  You can ignore this property under most common use cases, but not all.  The pre-processing style (used in `main.c`) avoids that property by accepting or rejecting all CM and *then* performing MMD processing on the result.)

Transclusion is similar and is handled before MMD processing.  Also, text can't properly be transcluded without knowledge of where the text came from, since relative file paths have to be calculated from a starting path.  As long as the MMD process has access to a file, then a user can enter arbitrary file paths to access that information.  This is a potentially *huge* security issue if run on servers, etc.  So file transclusion is intentionally separated from the core MMD library.

I do believe that these separate pieces need to be thought of independent in designing the proper workflow for your application.  What I have considered, however, is including a few more core functions in the `libMultiMarkdown.h` header file so that they can be used with fewer includes.

**Comment by fletcher** [comment]
v 6.0.7 incorporates some of the changes to `libMultiMarkdown.h` discussed above.

**Pull request closed without merging**
