### PR TITLE
Add @import support required for Swift

### PR DESCRIPTION
**Pull request by DivineDominion**
This assembles a .framework that is virtually indistinguishable from Xcode framework targets -- namely it's compatible with Swift and Objective-C.

1. To import the framework outside of C-based languages, `clang` needs a `.modulemap` to define a Module : https://clang.llvm.org/docs/Modules.html
2. The `cmake` instructions require Xcode-specific settings to use the modulemap in the .framework, and to find the output.

Overall very non-invasive changes. Unless the public header section changes, there's no need to touch the .modulemap.

Huge thanks to @mxgzf for maintaining our fork and then boiling it down to this!

### CODE REVIEW

**Comment by fletcher** [comment]
Thanks for doing this!

I don't currently use Swift for anything, so I have nothing to really test this with in a real life situation.  Is there anything else that is required?  Presumably I can get rid of the `cocoaconv.rb` script?

Is there anything else that I need to be careful about to avoid breaking Swift compatibility?  When I first experimented with Swift, the source files had to be in the `Sources` folder (or at least things worked much better if they were.)  It appears that is no longer the case (and probably has not been for quite a while).

**Comment by DivineDominion** [comment]
@fletcher I'm by no means a cmake wizard, but the automatic creation of the modulemap file does sound sensible! That would definitely solve the issue of maintaining 2 sources of truth. I'll have a look to see if I can figure that out.

With regard to "Swift" compatibility -- this is 1 of 2 possible ways to get libMMD into a Swift project at all. The route we took here is to make the `.framework` bundle compatible with Swift. In Xcode 12.5+, that is. If I remember correctly, with Xcode 11.x we initially had to do things a bit differently; then M1 Macs came along and the architecture dance started, etc. -- the settings from this PR are what is left over from this transitional period.

This PR does not offer Swift Package Manager support, though. It makes the framework do its job when you compile it and then drag & drop into your app, or embed it as a project in a workspace. If someone writes Swift projects with SwiftPM and no Xcode, this won't help out of the box. But it's not hard to combine both. It was way harder before this PR :)

Regarding `cocoaconv.rb`: the C enum case names are workable 🤷  And I bet the result is usable in SwiftPM, too. But it's not used at all bu this PR as we wanted to make it as simple as possible to get the framework settings merged. Could look into that at a later date, but feel free do delete my Ruby script for the time being to not drag it around.

**Comment by slsrepo** [comment]
@fletcher @mxgzf @DivineDominion Congrats! This is super nice for people building with CMake since now it will be possible to just drag the framework. Great job!

A word on Swift Package Manager support - this is irrelevant for Swift Package Manager since when building the package, the package manager automatically generates a module map from the headers in the include folder - but it's definitely nice, I updated the package manager repo for compatibility with the new module map :)

**Comment by fletcher** [comment]
@DivineDominion -- I spoke too soon.  Looks like the `XCODE_ATTRIBUTE_CONFIGURATION_BUILD_DIR` causes problems with other potential build configurations (namely mine when I pull libMultiMarkdown into other projects.)  Deleting that line restores functionality.

**Comment by DivineDominion** [comment]
@fletcher Could this be turned into a condition? Like 'if cmake is called with --swiftmodule flag, include these lines'?

**Comment by fletcher** [comment]
The problem is not necessarily with the built library, it's with the Cmake configuration.

I use a pretty consistent setup for most of my development work, which allows me to reuse shared components easily, and keep the code up to date when working on a shared library used across projects. (e.g. making fixes to libMultiMarkdown when it is used in a couple of macOS apps and a couple of iOS apps).

Ultimately, there are two general ways that I do this:

1. Use the library as a git submodule, and use Cmake to build the library from source and link/embed in the main app.  This is most useful when I am developing the main app using a relatively new library and need to make rapid changes to the library, or do detailed testing.
2. Built the library as a static library/framework and use the static library itself in the main app.  This is most useful when using a mature library that will not likely require a lot of testing, or when working on a shared project and wanting to separate the workflows between app development and library development.  In this case, I build and archive from the library Cmake project, and then copy the resulting binary to the "parent" Cmake folder

In this instance, I use libMultiMarkdown in a lot of places, and use the first approach.  When trying to use your changes, it breaks, since the framework does not end up where expected.

I'll be the first to admit that I could be doing things incorrectly in Cmake, and if there is a better way to do it I am happy to try.  That said, the approach I use has been refined over many years, and across many projects with a variety of structures.  So, perhaps it could be described as "battle-tested" but not necessarily "theoretically correct"???  :)

My question can probably be summarized as, "Why do you need to change the build directory just because you want to use Swift instead of Objective-C?"

**Comment by DivineDominion** [comment]
I see. The way I superficially understand this: it's not just for Swift, it's for Clang modules: https://clang.llvm.org/docs/Modules.html 

For Objective-C, you point the search paths somewhere related and then need to import the header and that's it. This is the trusted and true `#import <Foo/Foo.h>` way. With Clang modules, the ability to bundle things up a bit differently was introduced, allowing `@import Foo;` instead, which almost nobody used in ObjC I think :)  The link above does a better job at explaining things than I can, and the page isn't that long.

In other words: you're using a traditional C way to set stuff up. That's not necessarily bad, but you're sacrificing forward compatibility, so to speak, with anything that uses  clang (llvm?) modules. Which is `@import`  in ObjC, and Swift, but also Rust and Kotlin (native), and other llvm-based programming languages.

Since this is your library, it's ultimately your call to insist on C (and ObjC) compatibility only.

It's a pragmatic choice: given Swift's trajectory, I'd find that decision to be odd _if you want lib usage to increase_, but it's not a total deal breaker as all one needs is a little fix to bring your CMakeList instructions to the current day and age. And then there's SwiftPM and @slsrepo's work. Which doesn't work with Rust or Kotlin, obviously, but I don't know if that's a concern anyway.

**Comment by slsrepo** [comment]
I was going to write a very similar response, but Christian beat me to it and explained it remarkably well :)

Indeed, the answer to the question is that the difference between the two approaches is that in Swift you import Swift modules - instead of including frameworks/libraries (which you can still do in a bridging header though).

Over the years, Apple built multiple ways to help import these Swift modules - a few examples are picking up Clang module maps from frameworks, the SwiftPM build and packages system or XCFrameworks (that are sort of a mix between the previous two ways).

I don't have enough experience with CMake to determine if you did anything wrong, but as you mentioned and Christian noted, I think that it's probably fine, especially since it's been working for several years quite nicely and considering the fact you are focused on C and Obj-C.

While it is completely up to you, I agree with Christian about increasing the lib usage. I love MultiMarkdown and the exceptional work you are doing and I would like for it to be usable wherever possible - I've been doing whatever I can to progress that goal through the years (whether by creating libraries/gems/packages with the executable for PHP, Ruby and Python or the WordPress plugin, maintaining the SwiftPM fork, or other things I'm currently working on for Swift) and I think Rust support (maybe Go too?) would also be useful.

I also understand your intention though, as we discussed in the past, You are focusing on C - if someone is using Swift or Rust for example - they might have some insights you wouldn't likely have and then that person is probably better off maintaining it on their own with your external support (or advices).

**Comment by fletcher** [comment]
@DivineDominion and @slsrepo  -- Thanks for the comments, though I'm not sure either of you actually answered my question.  Are you certain the line in question (not the other changes) is necessary?

As to my goals -- MultiMarkdown should be able to be compiled and used on (almost) any operating system.  And while I understand that Swift has all the new shiny, I'm not certain that it is better than C (at least not yet.)  Throw in all the challenges over the years when Apple updates to a new version of Swift, and I am certain that it was not the best choice at the time.   Regardless, my intent is not to start a religious war over Swift (I am confident it has its uses).

I will definitely not be doing anything to intentionally break compatibility with any major operating system unless there is no good alternative.

And I am happy to include support for Swift, provided it doesn't break things.

My question is simply that you ensure that the `XCODE_ATTRIBUTE_CONFIGURATION_BUILD_DIR` line is actually necessary and correct.  For the moment I am leaving it alone, but will eventually revert that line since it is breaking things.

**Comment by fletcher** [comment]
And so that this doesn't get lost amongst the troubleshooting, I am appreciative of what you've both done so far!!

**Comment by slsrepo** [comment]
> @DivineDominion and @slsrepo -- Thanks for the comments, though I'm not sure either of you actually answered my question. Are you certain the line in question (not the other changes) is necessary?

Oops, I tried answering this question:
> My question can probably be summarized as, "Why do you need to change the build directory just because you want to use Swift instead of Objective-C?

Sorry :)

As I said, I'm not super experienced with CMake but I think that the line containing `XCODE_ATTRIBUTE_CONFIGURATION_BUILD_DIR` is necessary, although it might not be correct.

There are several issues with.
* This passage from the [CMake documentation about `XCODE_ATTRIBUTE`](https://cmake.org/cmake/help/v3.21/variable/CMAKE_XCODE_ATTRIBUTE_an-attribute.html?highlight=xcode_attribute%20break%things) implies there might be better ways to have the folder path there.
> This offers low-level control over the generated Xcode project file. It is meant as a **last resort** for specifying settings that CMake does not otherwise have a way to control. Although this can override a setting CMake normally produces on its own, doing so **bypasses CMake's model of the project and can break things**.
* It seems like [`CONFIGURATION` is deprecated](https://cmake.org/cmake/help/v3.21/manual/cmake-generator-expressions.7.html?highlight=configuration#id2) and `CONFIG` should be used instead.
* I also think the variables need to be wrapped in curly braces, so that the environment variables get evaluated? - `XCODE_ATTRIBUTE_CONFIGURATION_BUILD_DIR "${SYMROOT}/${CONFIGURATION}"` instead of `XCODE_ATTRIBUTE_CONFIGURATION_BUILD_DIR "$SYMROOT/$CONFIGURATION"`.

> I will definitely not be doing anything to intentionally break compatibility with any major operating system unless there is no good alternative.
>
> And I am happy to include support for Swift, provided it doesn't break things.

I definitely understand and agree that adding support for Swift shouldn't break anything else.
About alternative approaches, I mentioned them above - 
* Compiling without the generated Xcode project, using `swiftc` or `xcrun` and [CMake's `SWIFT_MODULE_DIRECTORY`](https://cmake.org/cmake/help/latest/prop_tgt/Swift_MODULE_DIRECTORY.html) instead of `XCODE_ATTRIBUTE_CONFIGURATION_BUILD_DIR`. (Relevant links [1](https://forums.swift.org/t/announcing-swift-support-in-cmake/24792), [2](https://github.com/compnerd/swift-cmake-examples), [3](https://blog.spencerkohan.com/building-swift-without-a-build-system/)).  Maybe as a .xcframework?
* The SwiftPM way, which shouldn't break anything since it runs separately from CMake. Although optionally, adding a command to CMake to run `swift build` on the swift folder should be really easy too.

> As to my goals -- MultiMarkdown should be able to be compiled and used on (almost) any operating system. And while I understand that Swift has all the new shiny, I'm not certain that it is better than C (at least not yet.) Throw in all the challenges over the years when Apple updates to a new version of Swift, and I am certain that it was not the best choice at the time. Regardless, my intent is not to start a religious war over Swift (I am confident it has its uses).

No religious war intended :) I still use C and Obj-C, C is still better performance wise, is more ubiquitous and you are definitely right that Swift was challenging to work with before maturing to ABI Stability - but since then it improved exponentially, it just keeps improving and it's running on many operating systems right now beyond just Apple's (Windows, Linux, Android, FreeBSD, Cygwin..., it's all in [Swift's CMakeLists.txt (😂)](https://github.com/apple/swift/blob/main/CMakeLists.txt)).

> And so that this doesn't get lost amongst the troubleshooting, I am appreciative of what you've both done so far!!

Thanks 🙏☺️

**Comment by DivineDominion** [comment]
@fletcher
It looks like `$SYMROOT/$CONFIGURATION` is the default value of `CONFIGURATION_BUILD_DIR` in Xcode:
 https://developer.apple.com/library/archive/documentation/DeveloperTools/Reference/XcodeBuildSettingRef/1-Build_Setting_Reference/build_setting_ref.html#//apple_ref/doc/uid/TP40003931-CH3-SW40

Experimenting with this value in isolation made me realize what is actually going to happen here -- instead of putting the build product into `./MultiMarkdown-6/build-xcode/{Debug|Release}/libMultiMarkdown.framework`, the product was created in the Xcode project's Derived Data location for build products, next to `MyApp.app` and `OtherLib.framework` etc.

So if you don't want to support the default build tools out of the box, projects checking out  libMMD6 as a submodule need to add e.g. `$SRCROOT/Extern/MultiMarkdown-6/build-xcode/{Debug|Release}` to FRAMEWORK_SEARCH_PATHS.

**Pull request merged**
