### PR TITLE
FIXED: compiling with older gcc and used c standard

### PR DESCRIPTION
**Pull request by silvio**
Signed-off-by: Silvio Fricke <silvio.fricke@gmail.com>

### CODE REVIEW

**Comment by silvio** [comment]
Only a small fix. Is the master branch right for development?

**Comment by silvio** [comment]
rebased to develop.

**Comment by fletcher** [comment]
What does this change accomplish for you?

**Comment by silvio** [comment]
I have added ore description to the commit message.

**Comment by silvio** [comment]
Thanks!

**Pull request merged**
