### PR TITLE
Introduce TEXT_REPLACEMENT_CHAR for \uFFFC NSTextAttachment character

### LINKED ISSUE #216: Suggestion: add token type TEXT_REPLACEMENT_CHARACTER to ease skipping NSTextAttachments
Text Kit on iOS and macOS uses the ["Object Replacement Character" (U+FFFC, "\u{0000fffc}")](https://unicode-table.com/en/FFFC/) to denote rich text contents or decorations inside text.

The way this works is basically that this is a zero-length character in the string, and there's a text attribute (the key is [`NSAttachmentAttributeName`](https://developer.apple.com/documentation/uikit/nsattachmentattributename?language=objc)) that is e.g. of the type `NSTextAttachment`.

Setting this is useful to show inline views in editors -- like images, buttons, "pills" (i.e. the tokens of token fields).

If MMD6 recognizes this character as a special case, it'd be easier to keep the attribute around. Could be a sibling to the `TEXT_PLAIN` token type, or maybe even a child, because it's _both_ plain text _and_ a replacement character, like `TEXT_REPLACEMENT_CHARACTER`.

The character is irrelevant when converting to e.g. HTML and should be skipped; for syntax highlighting, it's quite useful though.

### PR DESCRIPTION
**Pull request by DivineDominion**
Closes #216

    100% tests passed, 0 tests failed out of 11

When a text attachment is part of the input string, this  changes `TEXT_PLAIN` for the whole range into `TEXT_PLAIN` before the attachment, `TEXT_REPLACEMENT_CHAR` at the attachment location, and `TEST_PLAIN` afterwards again.

### CODE REVIEW

**Comment by DivineDominion** [comment]
@fletcher This is probably not enough for release, but meant to get some of the grunt work done so you don't have to.

**Comment by fletcher** [comment]
Ok.  I'll take a look at it when I get a chance.  If it hasn't been resolved in a week or two, feel free to ping me. (I'm in the middle of a bunch of things and not sure when I can dig into this.)

Thanks!

**Comment by DivineDominion** [comment]
Can report that this appears to work surprisingly well considering this is my first attempt to modify a generated parser :) 

Screen Shot 2021-07-11 at 10 14 11

```
{0,76}TokenType.blockPara
  {0,10}TokenType.pairBracketImage
    {0,2}TokenType.bracketImageLeft
    {2,7}TokenType.textPlain
    {9,1}TokenType.bracketRight
  {10,62}TokenType.pairParen
    {10,1}TokenType.parenLeft
    {11,1}TokenType.slash
    {12,5}TokenType.textPlain
    {17,1}TokenType.slash
    {18,3}TokenType.textPlain
    {21,1}TokenType.slash
    {22,9}TokenType.textPlain
    {31,1}TokenType.slash
    {32,7}TokenType.textPlain
    {39,1}TokenType.slash
    {40,10}TokenType.textPlain
    {50,1}TokenType.slash
    {51,3}TokenType.textPlain
    {54,1}TokenType.slash
    {55,5}TokenType.textPlain
    {60,1}TokenType.slash
    {61,4}TokenType.textPlain
    {65,1}TokenType.slash
    {66,5}TokenType.textPlain
    {71,1}TokenType.parenRight
  {72,3}TokenType.textReplacementChar           <----- this used to be .textPlain
  {75,1}TokenType.textNl
{76,1}TokenType.blockEmpty
  {76,1}TokenType.textNl
{77,30}TokenType.blockPara
  {77,5}TokenType.textPlain
  {82,12}TokenType.pairStrong
    {82,2}TokenType.strongStart
    {84,8}TokenType.textPlain
    {92,2}TokenType.strongStop
  {94,13}TokenType.textPlain
```

**Comment by fletcher** [comment]
I reimplemented this rather than merging the request.

1. Since this character is not part of plain text, I think it should be named differently.  I used OBJECT_REPLACEMENT_CHARACTER to be consistent with Unicode, since it has no meaning within Markdown/MultiMarkdown.

2. New token types have to be addressed in each of the output formats to prevent potential errors of an unrecognized token type.

I pushed to the develop branch.


Thanks!!!

**Pull request closed without merging**
